# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [35]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [36]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [37]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [38]:
chipo['item_price'] = pd.to_numeric(chipo['item_price'].astype(str).str.replace('$', ''), errors= 'coerce') # Cuando se produce un error produce un NaN

chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

In [39]:
print(chipo.loc[chipo['item_price'].idxmax(), ['item_name', 'item_price', 'quantity']]) # Producto más caro

item_name     Chips and Fresh Tomato Salsa
item_price                           44.25
quantity                                15
Name: 3598, dtype: object

In [40]:
chipo['unit_price'] = chipo['item_price'] / chipo['quantity'] # Producto más caro por unidad
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [41]:
print(chipo.loc[chipo['unit_price'].idxmax(), ['item_name', 'item_price', 'quantity', 'unit_price']])

item_name     Steak Salad Bowl
item_price               23.78
quantity                     2
unit_price               11.89
Name: 281, dtype: object

In [51]:
# Más de un producto
productos_caros = chipo[chipo['unit_price'] == chipo['unit_price'].max()]
print(productos_caros['item_name'].unique())

<StringArray>
['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl']
Length: 3, dtype: str

### Step 4. How many products cost more than $10.00?

In [49]:
chipo[chipo['unit_price'] > 10.00][['item_name', 'item_price']]

               item_name  item_price
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
39         Barbacoa Bowl       11.75
...                  ...         ...
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1034 rows x 2 columns]

In [33]:
print((chipo['item_price'] > 10).nunique())

2

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [62]:
chipo.loc[chipo['unit_price'] > 10]['order_id'].nunique()

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [67]:
print(chipo.groupby('order_id')['item_price'].sum())

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64

In [69]:
print((chipo.groupby('order_id')['item_price'].sum() > 10).sum())

#groupby('order_id'): agrupa las filas por pedido.
#['item_price'].sum(): suma el precio de los artículos de cada pedido.
#> 10: comprueba qué pedidos superan los 10.
#.sum(): cuenta los True, porque en Python True vale 1 y False vale 0.

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [73]:
print(chipo.loc[(chipo['item_price']>10) & (chipo['quantity']>1), 'order_id'].nunique())

117

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [8]:
chipo['unit_price'] = chipo['item_price'] / chipo['quantity']
chipo[['item_name', 'unit_price']]

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [74]:
chipo.sort_values(by= 'item_name')

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [75]:
print(chipo.loc[chipo['item_price'].idxmax(), 'quantity'])

15

In [ ]:
print(chipo.sort_values('item_price', ascending=False)['quantity'].iloc[0])
#sort_values('item_price', ascending=False): ordena las filas de mayor a menor precio.
#['quantity']: selecciona únicamente la columna de cantidad.
#.iloc[0]: obtiene el primer valor, es decir, la cantidad de la fila con el precio más alto.
#print(...): muestra el resultado.

15

In [ ]:
idx_implicito = chipo['item_price'].argmax()
idx_explicito = chipo['item_price'].idxmax()

In [82]:
#usamos chipo para ver lo de los ínidces implícitos y explícitos
#chipo['item_price'].idxmax() devuelve el índice explícito
#en chipo los índices explícitos sí hacen referencia al mismo producto
print(chipo.loc[idx_explicito, 'quantity'])

15

In [83]:
#iloc devuelve el índice implícito
print(chipo.iloc[idx_implicito]['quantity'])

15

In [85]:
print(chipo.iloc[chipo['item_price'].argmax()]['quantity'])

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [86]:
# Cuantas veces esta la ensalada
#Primero tenemos la condición que devuelve true en las que hay veggies
#Luego usamos estos True
print((chipo['item_name'] == 'Veggie Salad Bowl').sum())

18

### Step 9. How many times did someone order more than one Canned Soda?

In [104]:
chipo.loc[(chipo["item_name"] == "Canned Soda") & (chipo['quantity']>1), "order_id"].nunique()

18

In [105]:
chipo.loc[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1), 'order_id'] # En el pedido 450 y 1156 se pidieron 2

18         9
51        23
162       73
171       76
350      150
352      151
698      287
700      288
909      376
1091     450
1092     450
1944     787
2135     859
2235     901
2905    1156
2906    1156
3152    1258
3364    1349
3592    1440
3866    1550
Name: order_id, dtype: int64

In [97]:
chipo.loc[chipo['order_id'] == 450]

,order_id,quantity,item_name,choice_description,item_price,unit_price
1091,450,2,Canned Soda,[Dr. Pepper],2.18,1.09
1092,450,2,Canned Soda,[Coca Cola],2.18,1.09
1093,450,1,Steak Burrito,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",11.48,11.48

In [96]:
chipo.loc[chipo['order_id'] == 1156]

,order_id,quantity,item_name,choice_description,item_price,unit_price
2905,1156,2,Canned Soda,[Coca Cola],2.18,1.09
2906,1156,2,Canned Soda,[Sprite],2.18,1.09
2907,1156,1,Chips and Roasted Chili-Corn Salsa,NaN,2.39,2.39
2908,1156,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa (Medium), [Cheese, S...",8.49,8.49
2909,1156,1,Steak Burrito,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.99,8.99
2910,1156,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39